ports:
  - port: 8080
    visibility: public
tasks:
  - init: psql < DDL.sql
image: gitpod/workspace-postgres

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - pivotal.vscode-spring-boot